
package Formularios;

import Metodos.MetodosDaProdutora;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistema.Filmes;
import Metodos.MetodosDoFilme;
import sistema.Produtora;

/**
 *
 * @author tsaman.sumbane
 */
public class JFrmFilmes extends javax.swing.JFrame {
     Vector<Filmes> listaDeFilmes =null;
     Vector <Produtora> lista=null;
      
    /**
     * Creates new form JFrmFilmes
     */
    public JFrmFilmes() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilme = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxProdutora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblCodigo.setText("Codigo");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(30, 80, 60, 22);
        getContentPane().add(txtGenero);
        txtGenero.setBounds(140, 250, 230, 28);
        getContentPane().add(txtNome);
        txtNome.setBounds(30, 180, 340, 28);

        lblNome.setText("Titulo");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 150, 35, 22);

        lblGenero.setText("Genero");
        getContentPane().add(lblGenero);
        lblGenero.setBounds(140, 230, 60, 14);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(30, 110, 340, 28);

        lblAno.setText("Ano");
        getContentPane().add(lblAno);
        lblAno.setBounds(30, 220, 32, 24);
        getContentPane().add(txtAno);
        txtAno.setBounds(30, 250, 90, 28);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(430, 110, 90, 30);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(430, 190, 90, 30);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(430, 150, 90, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FILMES");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 20, 280, 40);

        tabelaFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Genero", "Ano", "Produtora"
            }
        ));
        tabelaFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFilme);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 830, 200);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(430, 230, 90, 30);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(570, 110, 140, 30);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(740, 110, 90, 30);

        jLabel2.setText("Produtora");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 290, 60, 14);

        getContentPane().add(comboBoxProdutora);
        comboBoxProdutora.setBounds(30, 310, 340, 30);

        setSize(new java.awt.Dimension(868, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
         
         String codigo= txtCodigo.getText();
         String nome= txtNome.getText();
         String genero = txtGenero.getText();
         String ano = txtAno.getText();
         String codigoProdutora = comboBoxProdutora.getSelectedItem()+"";
        
        try{
               MetodosDoFilme.adicionarFilmeNoFicheiro(codigo, nome, genero, ano, codigoProdutora);
           limparCaixasDeTexto();
            JOptionPane.showMessageDialog(null, "adicionado com sucesso");
        }catch (IOException e){
            JOptionPane.showMessageDialog(null,"nao foi possivel adicionar");
        }
                       
		
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void limparCaixasDeTexto()
    {
        txtCodigo.setText("");
        txtNome.setText("");
        txtGenero.setText("");
        txtAno.setText("");
    }
public void listar(){
         DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaFilme.getModel();
        modeloDaTabela.setNumRows(0);
        try{
            listaDeFilmes=MetodosDoFilme.listaDeFilme();
           for(Filmes filmes: listaDeFilmes){
            modeloDaTabela.addRow(new Object[]{
                filmes.getCodigo(),
                filmes.getNome(),
                filmes.getGenero(),
                filmes.getAno(),
                
                filmes.getCodigoProdutora(),

            });
           
           }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "nao foi possivel listar");
        }
    }
  
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
         listar();
    }//GEN-LAST:event_btnListarActionPerformed
    
    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            String codigo= txtCodigo.getText();
        String nome= txtNome.getText();
        String genero = txtGenero.getText();
       String ano = txtAno.getText();
       
        try
        {
             listaDeFilmes=MetodosDoFilme.listaDeFilme();
            MetodosDoFilme.atualizarFilme(listaDeFilmes, codigo, nome, genero, ano);
            JOptionPane.showMessageDialog(null, "atualizado com sucesso");
            limparCaixasDeTexto();
    
        }catch(IOException e1){
            JOptionPane.showMessageDialog(null, "nao foi possivel");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmeMouseClicked
       if(tabelaFilme.getSelectedRow()!=-1){
            int indice= tabelaFilme.getSelectedRow();
            TableModel modelo=tabelaFilme.getModel();
            txtCodigo.setText(modelo.getValueAt(indice,0).toString());
            txtNome.setText(modelo.getValueAt(indice,1).toString());
            txtGenero.setText(modelo.getValueAt(indice,2).toString());
            txtAno.setText(modelo.getValueAt(indice,3).toString());
            
            
        }
    }//GEN-LAST:event_tabelaFilmeMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String codigo = txtPesquisar.getText();
        String nome = txtPesquisar.getText();
        String genero = txtPesquisar.getText();
        String ano = txtPesquisar.getText();
        
        try {
            DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaFilme.getModel();
            modeloDaTabela.setNumRows(0);
            listaDeFilmes=MetodosDoFilme.listaDeFilme();
            for (Filmes filme : listaDeFilmes) {
                if (filme.getCodigo().equalsIgnoreCase(codigo)|| filme.getNome().equalsIgnoreCase(nome) || filme.getGenero().equalsIgnoreCase(genero) ||  filme.getAno().equalsIgnoreCase(ano)){
                    modeloDaTabela.addRow(new Object []{
                     filme.getCodigo(),
                     filme.getNome(),
                     filme.getGenero(),
                     filme.getAno(),
                     filme.getCodigoProdutora()
                     
                             });
                } 
                    
            } 
            
        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
         String codigo = txtCodigo.getText();
        String nome = txtNome.getText();
        String genero = txtGenero.getText();
        String ano = txtAno.getText();
        
        try {
            listaDeFilmes=MetodosDoFilme.listaDeFilme();
            MetodosDoFilme.removerFilme(listaDeFilmes, nome);
            JOptionPane.showMessageDialog(null, "O filme foi removido com sucesso");
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(null, "Error");
            
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         
        try { 
            
             lista=MetodosDaProdutora.listaDaProdutora();
                for (Produtora s : lista) {
                 comboBoxProdutora.addItem(s.getNome_produtora());
                 
                 
             
        
         }
       } catch (IOException ex) {                
             Logger.getLogger(JFrmFilmes.class.getName()).log(Level.SEVERE, null, ex);
         }                
    }//GEN-LAST:event_formWindowActivated
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> comboBoxProdutora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tabelaFilme;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
