/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.MetodosDoElenco;
import Metodos.MetodosDoFilme;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistema.Elenco;
import sistema.Filmes;

/**
 *
 * @author Mateus
 */
public class JFrmElenco extends javax.swing.JFrame {
     Vector<Filmes> listaDeFilmes =null;
      Vector<Elenco> lista =null;
    /**
     * Creates new form JFrmElenco
     */
    public JFrmElenco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboBoxFilme = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaElenco = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ELENCO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 90, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 20, 300, 40);

        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 50, 20);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(30, 140, 250, 30);

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 190, 40, 14);
        getContentPane().add(txtNome);
        txtNome.setBounds(30, 210, 250, 130);

        jLabel4.setText("Filme");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 350, 60, 20);

        getContentPane().add(comboBoxFilme);
        comboBoxFilme.setBounds(30, 380, 250, 30);

        tabelaElenco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Filme"
            }
        ));
        jScrollPane1.setViewportView(tabelaElenco);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 450, 900, 230);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(350, 140, 160, 60);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(350, 220, 160, 60);

        btnAtualizar.setText("Atualizar");
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(350, 300, 160, 60);

        setSize(new java.awt.Dimension(953, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void listar(){
         DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaElenco.getModel();
        modeloDaTabela.setNumRows(0);
        try{
            
            lista=MetodosDoElenco.listaDoElenco();
           for(Elenco elenco: lista){
            modeloDaTabela.addRow(new Object[]{
                elenco.getCodigo(),
                elenco.getNome(),
                elenco.getCodigoFilme(),
          
            });
           
           }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "nao foi possivel listar");
        }
    }
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
         listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String codigo = txtCodigo.getText();
        String nome = txtNome.getText();
        String codigoFilme = comboBoxFilme.getSelectedItem()+"";
        
         try {
             MetodosDoElenco.adicionarElencoNoFicheiro(codigo, nome, codigoFilme);
             JOptionPane.showMessageDialog(null, "Sucesso!");
         } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error 404 not found");
         }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(tabelaElenco.getSelectedRow()!=-1){
            int indice= tabelaElenco.getSelectedRow();
            TableModel modelo=tabelaElenco.getModel();
            txtCodigo.setText(modelo.getValueAt(indice,0).toString());
            txtNome.setText(modelo.getValueAt(indice,1).toString());     
        }       
    }//GEN-LAST:event_formMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         try {
                listaDeFilmes=MetodosDoFilme.listaDeFilme();
                for (Filmes s : listaDeFilmes) {
                 comboBoxFilme.addItem(s.getNome());
     
                 }             
        } catch (IOException ex) {
                Logger.getLogger(JFrnFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmElenco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboBoxFilme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaElenco;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
