/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.io.IOException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistema.Cliente;
import Metodos.MetodosDoCliente;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tsaman.sumbane
 */
public class JFrmCliente extends javax.swing.JFrame {
    Vector <Cliente> cl =null;
    String nome, bi, contacto;
    
    /**
     * Creates new form JFrmCliente
     */
    public JFrmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Bilhete de identidade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 170, 116, 20);
        getContentPane().add(txtContacto);
        txtContacto.setBounds(60, 330, 360, 30);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 240, 50, 14);

        txtBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiActionPerformed(evt);
            }
        });
        getContentPane().add(txtBi);
        txtBi.setBounds(60, 200, 360, 30);

        jLabel3.setText("Contacto");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 300, 90, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 260, 360, 30);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(480, 210, 90, 40);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(480, 110, 90, 40);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(480, 160, 90, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 10, 320, 40);

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Bilhete de identidade", "Nome", "Contacto"
            }
        ));
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCliente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 380, 680, 190);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(480, 260, 90, 40);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(620, 110, 150, 30);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(790, 110, 90, 30);

        jLabel5.setText("Código");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 110, 50, 14);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(60, 130, 360, 30);

        setSize(new java.awt.Dimension(907, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
if(tabelaCliente.getSelectedRow()!=-1){
            int indice= tabelaCliente.getSelectedRow();
            TableModel modelo=tabelaCliente.getModel();
            txtCodigo.setText(modelo.getValueAt(indice,0).toString());
            txtBi.setText(modelo.getValueAt(indice,1).toString());
            txtNome.setText(modelo.getValueAt(indice,2).toString());
            txtContacto.setText(modelo.getValueAt(indice,3).toString());
                 
        }           

        
    }//GEN-LAST:event_tabelaClienteMouseClicked
 public void listar () {
    DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaCliente.getModel();
        modeloDaTabela.setNumRows(0);
        try{
            cl=MetodosDoCliente.listaDoCliente();
           for(Cliente cliente : cl){
            modeloDaTabela.addRow(new Object[]{
                cliente.getCodigo(),
                cliente.getBi(),
                cliente.getNome(),
                cliente.getContacto()
                
            });
           
           }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "nao foi possivel listar");
        }
 }  
                
    
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        String codigo = txtCodigo.getText();
        String bi = txtBi.getText();
        String nome = txtNome.getText();
        String contacto = txtContacto.getText();
        
        try {
            MetodosDoCliente.adicionarCliente(codigo, bi, nome, contacto);
            listar();
            limparCaixaDeTextos();
            JOptionPane.showMessageDialog(null, "adicionado com sucesso");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error 404 Not found");
        }
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    public void limparCaixaDeTextos() {
        txtCodigo.setText("");
        txtBi.setText("");
        txtNome.setText("");
        txtContacto.setText("");
}
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String bi= txtBi.getText();
        String nome = txtNome.getText();
        String contacto = txtContacto.getText();
       
        try
        {
             cl=MetodosDoCliente.listaDoCliente();
            MetodosDoCliente.atualizarCliente(cl, bi, nome, contacto);
            JOptionPane.showMessageDialog(null, "atualizado com sucesso");
            limparCaixaDeTextos();
           
    
        }catch(IOException e1){
            JOptionPane.showMessageDialog(null, "nao foi possivel");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
         String bi = txtBi.getText();
     
        try {
            cl=MetodosDoCliente.listaDoCliente();
            MetodosDoCliente.remover(cl, bi);
            JOptionPane.showMessageDialog(null, " removido com sucesso");
        } catch (IOException ex) {
            Logger.getLogger(JFrmDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       String bi = txtPesquisar.getText();
        String nome = txtPesquisar.getText();
        String contacto = txtPesquisar.getText();
        
        try {
            DefaultTableModel modeloDaTabela = (DefaultTableModel)tabelaCliente.getModel();
            modeloDaTabela.setNumRows(0);
            cl=MetodosDoCliente.listaDoCliente();
            for (Cliente cliente : cl) {
                if (cliente.getBi().equalsIgnoreCase(bi) || cliente.getNome().equalsIgnoreCase(nome)) {
                    modeloDaTabela.addRow(new Object [] {
                        cliente.getCodigo(),
                        cliente.getBi(),
                        cliente.getNome(),
                        cliente.getContacto()
                        
                    });
                }
                
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
             
    }//GEN-LAST:event_formWindowActivated

    private void txtBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtBi;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
