/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistema.Departamento;
import Metodos.MetodosDoDepartamento;

/**
 *
 * @author tsaman.sumbane
 */
public class JFrmDepartamento extends javax.swing.JFrame {
    Vector <Departamento> lista=null;
    String codigo_departamento, nome_departamento;
    /**
     * Creates new form JFrmDepartamento
     */
    public JFrmDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDep = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo do departamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 150, 20);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(40, 100, 400, 30);

        jLabel2.setText("Nome do departamento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 130, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(40, 180, 400, 30);

        tabelaDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do departamento", "Nome do departamento"
            }
        ));
        tabelaDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDep);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 230, 400, 240);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(480, 100, 90, 50);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(480, 160, 90, 50);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(480, 220, 90, 50);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(600, 100, 170, 30);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(790, 100, 100, 30);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(480, 280, 90, 50);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("DEPARTAMENTO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 10, 160, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 10, 340, 40);

        setBounds(0, 0, 936, 530);
    }// </editor-fold>//GEN-END:initComponents

    public void listar (){
       DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaDep.getModel();
        modeloDaTabela.setNumRows(0);
        try{
            lista=MetodosDoDepartamento.listaDeDepartamento();
           for(Departamento depar: lista){
            modeloDaTabela.addRow(new Object[]{
                depar.getCodigo_departamento(),
                depar.getNome_departamento()
                       
            });
           
           }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "nao foi possivel listar");
        }
    }
    public void limparCaixaDeText () {
        txtCodigo.setText("");
        txtNome.setText("");
    }
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
         codigo_departamento = txtCodigo.getText();
         nome_departamento= txtNome.getText();
        
        try {
            MetodosDoDepartamento.adicionarDepartamento(codigo_departamento, nome_departamento);
            JOptionPane.showMessageDialog(null, "Adicionado com sucesso");
            limparCaixaDeText();
            listar();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error 404 not found");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tabelaDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDepMouseClicked
        if(tabelaDep.getSelectedRow()!=-1){
            int indice= tabelaDep.getSelectedRow();
            TableModel modelo=tabelaDep.getModel();
            txtCodigo.setText(modelo.getValueAt(indice,0).toString());
            txtNome.setText(modelo.getValueAt(indice,1).toString());
        }
    }//GEN-LAST:event_tabelaDepMouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        codigo_departamento = txtCodigo.getText();
       nome_departamento = txtNome.getText();
       
       try {
           lista=MetodosDoDepartamento.listaDeDepartamento();
           MetodosDoDepartamento.atualizarDepartamento(lista, codigo_departamento, nome_departamento);
            JOptionPane.showMessageDialog(null, "atualizado com sucesso");
            limparCaixaDeText();
            listar();
    
        }catch(IOException e1){
            JOptionPane.showMessageDialog(null, "nao foi possivel");
        }
       
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String codigo_departamento = txtPesquisar.getText();
        String nome_departamento = txtPesquisar.getText();
        
        try {
            DefaultTableModel modeloDaTabela = (DefaultTableModel)tabelaDep.getModel();
            modeloDaTabela.setNumRows(0);
            lista=MetodosDoDepartamento.listaDeDepartamento();
            for (Departamento departamento : lista) {
                if (departamento.getCodigo_departamento().equalsIgnoreCase(nome_departamento) || departamento.getNome_departamento().equalsIgnoreCase(nome_departamento)) {
                    modeloDaTabela.addRow(new Object [] {
                        departamento.getCodigo_departamento(),
                        departamento.getNome_departamento()
                        
                    });
                }
                
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        String codigo_departanento = txtCodigo.getText();
      
        
        try {
            lista=MetodosDoDepartamento.listaDeDepartamento();
            MetodosDoDepartamento.removerDepartamento(lista, codigo_departamento);
            JOptionPane.showMessageDialog(null, "O departamento foi removido com sucesso");
        } catch (IOException ex) {
            Logger.getLogger(JFrmDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
              lista = MetodosDoDepartamento.listaDeDepartamento();
              int codigo = MetodosDoDepartamento.linhasDoFicheiro();
              txtCodigo.setText((codigo+1)+"");
             
          } catch (IOException ex) {        
            Logger.getLogger(JFrmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDep;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
