/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistema.Departamento;
import sistema.Funcionario;
import Metodos.MetodosDoDepartamento;
import Metodos.MetodosDoFuncionario;

/**
 *
 * @author Devil
 */
public class JFrnFuncionario extends javax.swing.JFrame {
        Vector<Funcionario> func =null;
  
    Vector<Departamento>dep=null;
  
 
    
    /**
     * Creates new form JFrnFuncionario
     */
    public JFrnFuncionario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bntAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblCodigo.setText("Código");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(40, 80, 70, 14);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(40, 100, 400, 29);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 140, 80, 14);
        getContentPane().add(txtNome);
        txtNome.setBounds(40, 160, 400, 30);
        getContentPane().add(txtContacto);
        txtContacto.setBounds(40, 220, 400, 29);

        jLabel2.setText("Contacto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 90, 14);

        jLabel3.setText("Departamento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 340, 110, 14);

        bntAdicionar.setText("Adicionar");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(bntAdicionar);
        bntAdicionar.setBounds(500, 90, 130, 60);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(500, 230, 130, 60);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(500, 160, 130, 60);

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Contacto", "Departamento", "Sexo"
            }
        ));
        tabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaFuncionario);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 410, 940, 210);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("FUNCIONÁRIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel4)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 10, 450, 40);

        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox);
        ComboBox.setBounds(40, 360, 140, 30);

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(670, 90, 170, 30);

        btnPesquisar.setText("Pesqusiar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(860, 90, 110, 30);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(500, 300, 130, 50);

        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 270, 24, 14);

        ComboBox1.setToolTipText("");
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox1);
        ComboBox1.setBounds(40, 290, 140, 30);

        setSize(new java.awt.Dimension(1027, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limparCaixaDeTexto () {
        txtCodigo.setText("");
        txtNome.setText("");
        txtContacto.setText("");
        
    }
    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
            
            ComboBox.removeAllItems(); 
            ComboBox1.removeAll();
            String codigo=txtCodigo.getText();
            String nome=txtNome.getText();
            String contacto=txtContacto.getText();
            String departamento = ComboBox.getSelectedItem()+ "";
            String sexo = ComboBox1.getSelectedItem()+"";
             
         
    try {
        MetodosDoFuncionario.adicionarFuncionarioNoFicheiro(codigo, nome, contacto, sexo, departamento);
        JOptionPane.showMessageDialog(null, "Adicionado com sucesso");
        limparCaixaDeTexto();
    }       catch (IOException ex) {        
              JOptionPane.showMessageDialog(null, "Error");  
            }        
            
        
    }//GEN-LAST:event_bntAdicionarActionPerformed

    public void listar(){
         DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaFuncionario.getModel();
        modeloDaTabela.setNumRows(0);
        try{
            func=MetodosDoFuncionario.listaDoFuncionario();
           for(Funcionario funcionario: func){
            modeloDaTabela.addRow(new Object[]{
                funcionario.getCodigo(),
                funcionario.getNome(),
                funcionario.getContacto(),
                funcionario.getSexo(),
                funcionario.getDepartamento()
            });
           
           }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "nao foi possivel listar");
        }
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void tabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionarioMouseClicked
       if(tabelaFuncionario.getSelectedRow()!=-1){
            int indice= tabelaFuncionario.getSelectedRow();
            TableModel modelo=tabelaFuncionario.getModel();
            txtCodigo.setText(modelo.getValueAt(indice,0).toString());
            txtNome.setText(modelo.getValueAt(indice,1).toString());
            txtContacto.setText(modelo.getValueAt(indice,2).toString());
           
                 
        }         
    }//GEN-LAST:event_tabelaFuncionarioMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String codigo= txtCodigo.getText();
        String nome = txtNome.getText();
        String contacto = txtContacto.getText();

        try
        {
             func=MetodosDoFuncionario.listaDoFuncionario();
            MetodosDoFuncionario.atualizarFuncionario(func, codigo, nome, contacto);
            JOptionPane.showMessageDialog(null, "atualizado com sucesso");
            limparCaixaDeTexto ();
    
        }catch(IOException e1){
            JOptionPane.showMessageDialog(null, "nao foi possivel");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            try {
                dep=MetodosDoDepartamento.listaDeDepartamento();
                for(Departamento dep1: dep){
                   ComboBox.addItem(dep1.getNome_departamento());
                   ComboBox1.removeAllItems();
                   
                   ComboBox1.addItem("Masculino");
                   ComboBox1.addItem("Feminino");
                   ComboBox1.addItem("Prefioro nao dizer");
                   
                   
                  
                   
                    
                   func = MetodosDoFuncionario.listaDoFuncionario();
                    
                    int codigo = MetodosDoFuncionario.linhasDoFicheiro();
                    txtCodigo.setText((codigo)+1+"");                }
            } catch (IOException ex) {
                Logger.getLogger(JFrnFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
    }//GEN-LAST:event_formWindowActivated

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       String codigo=txtPesquisar.getText();
        String nome = txtPesquisar.getText();
        String contacto = txtPesquisar.getText();
        
        try {
            DefaultTableModel modeloDaTabela= (DefaultTableModel)tabelaFuncionario.getModel();
            modeloDaTabela.setNumRows(0);
            func=MetodosDoFuncionario.listaDoFuncionario();
            for (Funcionario func : func) {
                if (func.getCodigo().equalsIgnoreCase(codigo)|| func.getNome().equalsIgnoreCase(nome) || func.getContacto().equalsIgnoreCase(contacto)){
                    modeloDaTabela.addRow(new Object []{
                     func.getCodigo(),
                     func.getNome(),
                     func.getContacto(),
                     func.getDepartamento(),
                     func.getSexo()
                     
                   });
                } 
                    
            } 
            
        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        String codigo = txtCodigo.getText();
        
            try {
                func = MetodosDoFuncionario.listaDoFuncionario();
                MetodosDoFuncionario.RemoverFuncionario(func, codigo);
                JOptionPane.showMessageDialog(null, "removido com sucesso");
            } catch (IOException ex) {
                 JOptionPane.showMessageDialog(null, "error");
            }
        
  
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrnFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrnFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrnFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrnFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrnFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
